### PR TITLE
Add new work of representation learning

### PR DESCRIPTION
**Pull request by enmanuelmag**
Add new personal work about classification and vectorization of key-frames and face characters of anime @SerialLain3170 .

### CODE REVIEW

**Comment by SerialLain3170** [comment]
Thank you for the pull request. Before deciding to merge, I have a question.

Is the paper for the conferences or the journal? Or, is it the result of your personal project? If the latter case is true, the work corresponds to [project](https://github.com/SerialLain3170/AwesomeAnimeResearch#projects).

**Comment by enmanuelmag** [comment]
> Thank you for the pull request. Before deciding to merge, I have a question.
> 
> Is the paper for the conference or the journal? Or, is it the result of your personal project? If the latter case is true, the work corresponds to [project](https://github.com/SerialLain3170/AwesomeAnimeResearch#projects).
> 
> 

Currently is only a personal project, I'll try tu submit on some conference but for now I'll change to project as you mention

**Comment by enmanuelmag** [comment]
@SerialLain3170 I made the changes

**Comment by SerialLain3170** [comment]
Thank you for your understanding. I'll merge.

**Pull request merged**
